# Railway configuration for Sahas Uyana Backend (API Server)
# This configuration is for deploying the Node.js/Express backend server

[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && node index.js"

[env]
NODE_ENV = "production"
# Make sure to set your actual MongoDB URI in Railway environment variables
# MONGODB_URI = "mongodb+srv://username:password@cluster.mongodb.net/database"
PORT = "5000"

[[services]]
name = "sahas-uyana-api"
rootDir = "server"
buildCommand = "npm install"
startCommand = "node index.js"
healthcheckPath = "/api/health"
port = 5000