# Railway configuration for Sahas Uyana Frontend (React App)
# This configuration is for deploying the React frontend application

[build]
builder = "nixpacks"

[deploy]
startCommand = "npm install && npm run build && npx serve -s build"

[env]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "sahas-uyana-frontend"
runtime = "nodejs"
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s build"
port = 3000